# Generated by Django 4.1.7 on 2023-02-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subscription_suscriptionfeature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuscriptionFeature',
            new_name='SubscriptionFeature',
        ),
    ]
