# Generated by Django 4.1.7 on 2023-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_suscriptionfeature_subscriptionfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionfeature',
            name='subs',
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='subs',
            field=models.ManyToManyField(to='main.subscription'),
        ),
    ]
