# Generated by Django 4.1.7 on 2023-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subscription_max_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_months', models.IntegerField()),
                ('total_discount', models.IntegerField()),
            ],
        ),
    ]
