# Generated by Django 4.1.7 on 2023-02-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_packagediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagediscount',
            name='subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subscription'),
        ),
    ]
