# Generated by Django 4.1.7 on 2023-02-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
