# Generated by Django 4.1.7 on 2023-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_assignsubscriber_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='validity_days',
            field=models.IntegerField(null=True),
        ),
    ]
