# Generated by Django 4.1.7 on 2023-02-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_subscriberplan_reg_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slider'},
        ),
    ]
