# Generated by Django 4.1.7 on 2023-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name_plural': "Trainer's Achievements"},
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
