# Generated by Django 4.1.7 on 2023-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_trainersalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainersalary',
            options={'verbose_name_plural': "Trainer's Salary"},
        ),
        migrations.AddField(
            model_name='trainersalary',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
